breakout-rainbow-all:
    env:
        grid_search:
             - Breakout-v0
             - Breakout-v4
             - BreakoutDeterministic-v4
             - BreakoutNoFrameskip-v4
    run: DQN
    stop:
        episode_reward_mean: 400
    config:
        num_atoms: 51
        noisy: True
        gamma: 0.99
        lr: .0001
        hiddens: [512]
        learning_starts: 10000
        buffer_size: 50000
        sample_batch_size: 4
        train_batch_size: 32
        schedule_max_timesteps: 2000000
        exploration_final_eps: 0.0
        exploration_fraction: .000001
        target_network_update_freq: 500
        prioritized_replay: True
        prioritized_replay_alpha: 0.5
        beta_annealing_fraction: 0.2
        final_prioritized_replay_beta: 1.0
        n_step: 3
        num_gpus: 1
        model:
          grayscale: True
          zero_mean: False
          dim: 42
